
POST https://ilv-part3-phonebook.herokuapp.com/api/persons HTTP/1.1
# POST http://localhost:3001/api/persons HTTP/1.1
content-type: application/json

{
    "name": "stop trying myman",
    "number": "123452323222"
}